### PR TITLE
ability to use participants helper on both client and server

### PR DESCRIPTION
**Pull request by Neobii**

### CODE REVIEW

**Comment by copleykj** [comment]
Yeah, I think what is happening here is that uId gets a value of undefined on the server and then just publishes every participant record for the conversation.. This is fine because I added the exclusion because I mean it to be used more as a template helper and it really didn't need show the current user that they were a participant in the conversation.

I think though if we don't mind the logged in user being added when run on the server, then the code could be structured to show this intent.

**Comment by Neobii** [comment]
For publications this is alright because the current user is published
anyway.

**Comment by Neobii** [comment]
However, I get that this isn't your original intention, but having cursors available like this is one of the best features of the packages for me.

**Comment by Neobii** [comment]
Maybe, you take out the exclusionary userId in the participants and let people handle it themselves with the user isSelf helper you made.

**Comment by copleykj** [comment]
ok there's an update that should resolve this.. I totally see where you are coming from. I just wanted to show explicitly the intent with the code, rather than having an undefined and possibly unexpected behavior if someone else where to read the code and not understand why the exclusion was not happening.

**Pull request closed without merging**
